version: '3'
services:

  server:
    image: karimtismail/server-repo
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  client:
    image: karimtismail/client-repo
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8080
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
